# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc4a14e184b8697b63929e67246d1871"
name = "moodclip-v2"
handle = "moodclip-v2-1"
application_url = "https://prep-duncan-morris-drilling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://prep-duncan-morris-drilling.trycloudflare.com/auth/callback", "https://prep-duncan-morris-drilling.trycloudflare.com/auth/shopify/callback", "https://prep-duncan-morris-drilling.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://prep-duncan-morris-drilling.trycloudflare.com"
subpath = "moodclip-uploader"
prefix = "apps"

[pos]
embedded = false
