# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc4a14e184b8697b63929e67246d1871"
name = "moodclip-v3"
handle = "moodclip-v3"
application_url = "https://moodclip-v2.onrender.com/"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://moodclip-v2.onrender.com/auth/callback",
  "https://moodclip-v2.onrender.com/auth/shopify/callback",
  "https://moodclip-v2.onrender.com/api/auth/callback"
]

[app_proxy]
# This URL must point to your production server, not a local tunnel.
url = "https://moodclip-v2.onrender.com/proxy"
subpath = "moodclip-uploader"
prefix = "apps"

[pos]
embedded = false
