# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bc4a14e184b8697b63929e67246d1871"
name = "moodclip-v2"
handle = "moodclip-v2-1"
application_url = "https://girl-deserve-totally-shares.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://girl-deserve-totally-shares.trycloudflare.com/auth/callback", "https://girl-deserve-totally-shares.trycloudflare.com/auth/shopify/callback", "https://girl-deserve-totally-shares.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://girl-deserve-totally-shares.trycloudflare.com"
subpath = "moodclip-uploader"
prefix = "apps"

[pos]
embedded = false
